package views;

import controllers.EmpleadosController;
import controllers.GeneticasController;
import controllers.HematologiasController;
import controllers.LiquidosController;
import controllers.MicrobiologiasController;
import controllers.MolecularesController;
import controllers.QuimicasController;
import controllers.SettingsController;
import models.Empleados;
import models.EmpleadosDao;
import models.Geneticas;
import models.GeneticasDao;
import models.Hematologias;
import models.HematologiasDao;
import models.Liquidos;
import models.LiquidosDao;
import models.Microbiologias;
import models.MicrobiologiasDao;
import models.Moleculares;
import models.MolecularesDao;
import models.Quimicas;
import models.QuimicasDao;

public class SystemView extends javax.swing.JFrame {

    //Empleados
    Empleados empleado = new Empleados();
    EmpleadosDao empleadosDao = new EmpleadosDao();
    //Quimica
    Quimicas quimica = new Quimicas();
    QuimicasDao quimicasDao = new QuimicasDao();
    //Hematologia
    Hematologias hematologia = new Hematologias();
    HematologiasDao hematologiasDao = new HematologiasDao();
    //Liquidos
    Liquidos liquido = new Liquidos();
    LiquidosDao liquidosDao = new LiquidosDao();
    //Molecular
    Moleculares molecular = new Moleculares();
    MolecularesDao molecularesDao = new MolecularesDao();
    //Microbiologia
    Microbiologias microbiologia = new Microbiologias();
    MicrobiologiasDao microbiologiasDao = new MicrobiologiasDao();
    //Geneticas
    Geneticas genetica = new Geneticas();
    GeneticasDao geneticasDao = new GeneticasDao();
    
    
    public SystemView() {
        initComponents();
        setSize(1208, 680);
        setResizable(false);
        setTitle("Panel de administración");
        setLocationRelativeTo(null);
        
        //Controlador de configuraciones
        SettingsController setting = new SettingsController(this);
        this.repaint();
        
        //Controlador de empleados
        EmpleadosController empleado_account = new EmpleadosController(empleado, empleadosDao, this);
        empleado_account.listAllEmpleados();
        
        //Controlador de quimicas
        QuimicasController quimica_accout = new QuimicasController(quimica, quimicasDao, this);
        quimica_accout.listAllQuimicas();
        
        //Controlador de hematologias
        HematologiasController hematologia_accout = new HematologiasController(hematologia, hematologiasDao, this);
        hematologia_accout.listAllHematologias();
        
        //Controlador de liquidos
        LiquidosController liquido_accout = new LiquidosController(liquido, liquidosDao, this);
        liquido_accout.listAllLiquidos();
        
        //Controlador de moleculares
        MolecularesController molecular_accout = new MolecularesController(molecular, molecularesDao, this);
        molecular_accout.listAllMoleculares();
        
        //Controlador de microbiologia
        MicrobiologiasController microbiologia_accout = new MicrobiologiasController(microbiologia, microbiologiasDao, this);
        microbiologia_accout.listAllMicrobiologias();
        
        //Controlador de geneticas
        GeneticasController geneticas_accout = new GeneticasController(genetica, geneticasDao, this);
        geneticas_accout.listAllGeneticas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelQuimica = new javax.swing.JPanel();
        jLabelQuimica = new javax.swing.JLabel();
        jPanelHematologia = new javax.swing.JPanel();
        jLabelHematologia = new javax.swing.JLabel();
        jPanelLiquidosCorporales = new javax.swing.JPanel();
        jLabelLiquidosCorporales = new javax.swing.JLabel();
        jPanelMicrobiologia = new javax.swing.JPanel();
        jLabelMicrobiologia = new javax.swing.JLabel();
        jPanelMolecular = new javax.swing.JPanel();
        jLabelMolecular = new javax.swing.JLabel();
        jPanelGeneticas = new javax.swing.JPanel();
        jLabelGenetica = new javax.swing.JLabel();
        jPanelCotizaciones = new javax.swing.JPanel();
        jLabelCotizaciones = new javax.swing.JLabel();
        jLabelEmpleados = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_photo = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_quimica_name = new javax.swing.JTextField();
        btn_register_quimica = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_quimica_price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_quimica_code = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btn_update_quimica = new javax.swing.JButton();
        btn_delete_quimica = new javax.swing.JButton();
        btn_cancel_quimica = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        quimicas_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_search_quimica = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txt_hematologia_code = new javax.swing.JTextField();
        txt_hematologia_name = new javax.swing.JTextField();
        txt_hematologia_price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_register_hematologia = new javax.swing.JButton();
        btn_update_hematologia = new javax.swing.JButton();
        btn_delete_hematologia = new javax.swing.JButton();
        btn_cancel_hematologia = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_search_hematologia = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        hematologias_table = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_liquido_code = new javax.swing.JTextField();
        txt_liquido_name = new javax.swing.JTextField();
        txt_liquido_price = new javax.swing.JTextField();
        btn_register_liquido = new javax.swing.JButton();
        btn_update_liquido = new javax.swing.JButton();
        btn_delete_liquido = new javax.swing.JButton();
        btn_cancel_liquido = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_search_liquidos = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        liquidos_table = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_molecular_code = new javax.swing.JTextField();
        txt_molecular_name = new javax.swing.JTextField();
        txt_molecular_price = new javax.swing.JTextField();
        btn_register_molecular = new javax.swing.JButton();
        btn_update_molecular = new javax.swing.JButton();
        btn_delete_molecular = new javax.swing.JButton();
        btn_cancel_molecular = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txt_search_moleculares = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        moleculares_table = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        txt_microbiologia_code = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_microbiologia_name = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_microbiologia_price = new javax.swing.JTextField();
        btn_register_microbiologia = new javax.swing.JButton();
        btn_update_microbiologia = new javax.swing.JButton();
        btn_delete_microbiologia = new javax.swing.JButton();
        btn_cancel_microbiologia = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txt_search_microbiologias = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        microbiologias_table = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txt_genetica_code = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_genetica_name = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_genetica_price = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        btn_register_genetica = new javax.swing.JButton();
        btn_update_genetica = new javax.swing.JButton();
        btn_delete_genetica = new javax.swing.JButton();
        btn_cancel_genetica = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txt_search_geneticas = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        geneticas_table = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        cmb_rol = new javax.swing.JComboBox<>();
        txt_empleado_username = new javax.swing.JTextField();
        txt_empleado_fullname = new javax.swing.JTextField();
        txt_empleado_id = new javax.swing.JTextField();
        txt_empleado_address = new javax.swing.JTextField();
        txt_empleado_telephone = new javax.swing.JTextField();
        txt_empleado_email = new javax.swing.JTextField();
        txt_empleado_password = new javax.swing.JPasswordField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        btn_register_employee = new javax.swing.JButton();
        btn_update_employee = new javax.swing.JButton();
        btn_delete_employee = new javax.swing.JButton();
        btn_cancel_employee = new javax.swing.JButton();
        txt_search_empleado = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        empleados_table = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(96, 112, 191));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelQuimica.setBackground(new java.awt.Color(96, 112, 191));

        jLabelQuimica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelQuimica.setForeground(new java.awt.Color(255, 255, 255));
        jLabelQuimica.setText("Quimica");

        javax.swing.GroupLayout jPanelQuimicaLayout = new javax.swing.GroupLayout(jPanelQuimica);
        jPanelQuimica.setLayout(jPanelQuimicaLayout);
        jPanelQuimicaLayout.setHorizontalGroup(
            jPanelQuimicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuimicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuimica, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelQuimicaLayout.setVerticalGroup(
            jPanelQuimicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQuimicaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelQuimica, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 35));

        jPanelHematologia.setBackground(new java.awt.Color(96, 112, 191));

        jLabelHematologia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelHematologia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHematologia.setText("Hematologia");

        javax.swing.GroupLayout jPanelHematologiaLayout = new javax.swing.GroupLayout(jPanelHematologia);
        jPanelHematologia.setLayout(jPanelHematologiaLayout);
        jPanelHematologiaLayout.setHorizontalGroup(
            jPanelHematologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHematologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHematologia, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHematologiaLayout.setVerticalGroup(
            jPanelHematologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHematologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHematologia, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelHematologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 35));

        jPanelLiquidosCorporales.setBackground(new java.awt.Color(96, 112, 191));

        jLabelLiquidosCorporales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLiquidosCorporales.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLiquidosCorporales.setText("Liquidos Corporales");

        javax.swing.GroupLayout jPanelLiquidosCorporalesLayout = new javax.swing.GroupLayout(jPanelLiquidosCorporales);
        jPanelLiquidosCorporales.setLayout(jPanelLiquidosCorporalesLayout);
        jPanelLiquidosCorporalesLayout.setHorizontalGroup(
            jPanelLiquidosCorporalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiquidosCorporalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLiquidosCorporales, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelLiquidosCorporalesLayout.setVerticalGroup(
            jPanelLiquidosCorporalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLiquidosCorporalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLiquidosCorporales, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelLiquidosCorporales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 35));

        jPanelMicrobiologia.setBackground(new java.awt.Color(96, 112, 191));

        jLabelMicrobiologia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMicrobiologia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMicrobiologia.setText("Microbiologia");

        javax.swing.GroupLayout jPanelMicrobiologiaLayout = new javax.swing.GroupLayout(jPanelMicrobiologia);
        jPanelMicrobiologia.setLayout(jPanelMicrobiologiaLayout);
        jPanelMicrobiologiaLayout.setHorizontalGroup(
            jPanelMicrobiologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMicrobiologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMicrobiologia, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMicrobiologiaLayout.setVerticalGroup(
            jPanelMicrobiologiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMicrobiologiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMicrobiologia, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelMicrobiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 35));

        jPanelMolecular.setBackground(new java.awt.Color(96, 112, 191));

        jLabelMolecular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMolecular.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMolecular.setText("Molecular");

        javax.swing.GroupLayout jPanelMolecularLayout = new javax.swing.GroupLayout(jPanelMolecular);
        jPanelMolecular.setLayout(jPanelMolecularLayout);
        jPanelMolecularLayout.setHorizontalGroup(
            jPanelMolecularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMolecularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMolecular, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMolecularLayout.setVerticalGroup(
            jPanelMolecularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMolecularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMolecular, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelMolecular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 35));

        jPanelGeneticas.setBackground(new java.awt.Color(96, 112, 191));

        jLabelGenetica.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelGenetica.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenetica.setText("Genetica");

        javax.swing.GroupLayout jPanelGeneticasLayout = new javax.swing.GroupLayout(jPanelGeneticas);
        jPanelGeneticas.setLayout(jPanelGeneticasLayout);
        jPanelGeneticasLayout.setHorizontalGroup(
            jPanelGeneticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGenetica, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelGeneticasLayout.setVerticalGroup(
            jPanelGeneticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeneticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGenetica, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelGeneticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 35));

        jPanelCotizaciones.setBackground(new java.awt.Color(96, 112, 191));

        jLabelCotizaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCotizaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCotizaciones.setText("Cotizaciones");

        javax.swing.GroupLayout jPanelCotizacionesLayout = new javax.swing.GroupLayout(jPanelCotizaciones);
        jPanelCotizaciones.setLayout(jPanelCotizacionesLayout);
        jPanelCotizacionesLayout.setHorizontalGroup(
            jPanelCotizacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCotizacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCotizaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCotizacionesLayout.setVerticalGroup(
            jPanelCotizacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCotizacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCotizaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanelCotizaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 200, 35));

        jLabelEmpleados.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmpleados.setText("Empleados");
        jPanel1.add(jLabelEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 370, 170, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 580));

        jPanel3.setBackground(new java.awt.Color(96, 112, 191));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LABORATORIO CLINICO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 340, 60));

        btn_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel3.add(btn_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 80, 65));

        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_logout.setText("Salir");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel3.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 35, 70, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1020, 100));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(107, 210, 214));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quimica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        btn_register_quimica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register_quimica.setText("Registrar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Precio:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Código:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Los exámenes sanguíneos de química son pruebas que se realizan en una muestra de sangre para evaluar el\nfuncionamiento de diferentes órganos y sistemas del cuerpo. Estas pruebas miden la cantidad y actividad\nde diversas sustancias químicas en la sangre, incluyendo electrolitos, enzimas, hormonas, proteínas y otros\ncompuestos.\n\nAlgunos de los exámenes sanguíneos de química más comunes incluyen el perfil metabólico completo, que\nevalúa la función hepática, renal y tiroidea, así como los niveles de glicemia y lípidos en la sangre. También\nexisten exámenes específicos para evaluar la función cardíaca, la salud ósea, los niveles de hierro, vitaminas\ny otros nutrientes en la sangre.\n\nLos resultados de los exámenes sanguíneos de química pueden proporcionar información valiosa sobre la\nsalud de una persona, ayudando a identificar enfermedades, afecciones y problemas de salud en etapa\ntemprana. Estos resultados son evaluados por un médico o profesional de la salud y pueden utilizarse para\nguiar el tratamiento y seguimiento médico de la persona.");
        jScrollPane3.setViewportView(jTextArea2);

        btn_update_quimica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update_quimica.setText("Modificar");

        btn_delete_quimica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete_quimica.setText("Eliminar");

        btn_cancel_quimica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel_quimica.setText("Cancelar");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txt_quimica_code, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_quimica_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txt_quimica_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cancel_quimica, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btn_delete_quimica, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btn_update_quimica, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(btn_register_quimica, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(62, 62, 62))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_register_quimica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_quimica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete_quimica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel_quimica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_quimica_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_quimica_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quimica_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 320));

        quimicas_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        jScrollPane2.setViewportView(quimicas_table);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 910, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Buscar:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        jPanel2.add(txt_search_quimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        jTabbedPane1.addTab("Quimica", jPanel2);

        jPanel4.setBackground(new java.awt.Color(107, 210, 214));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hematologia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Los exámenes sanguíneos de hematología son análisis de laboratorio que se utilizan para evaluar la salud de la sangre y los \ncomponentes sanguíneos. Estos exámenes incluyen la medición de la cantidad y calidad de los glóbulos rojos, blancos y plaquetas en\nla sangre, así como la evaluación de otras sustancias en la sangre, como la hemoglobina, el hematocrito y los  niveles de hierro. Estos\nexámenes son útiles para diagnosticar y monitorear una amplia variedad de enfermedades, como  anemia, leucemia, enfermedades\ndel sistema inmunológico y trastornos de coagulación sanguínea. Los resultados de estos exámenes también pueden ayudar a los\nmédicos a evaluar la efectividad del tratamiento y a determinar la necesidad de intervenciones médicas adicionales.");
        jScrollPane1.setViewportView(jTextArea1);

        txt_hematologia_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hematologia_nameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Código:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Precio:");

        btn_register_hematologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register_hematologia.setText("Registrar");

        btn_update_hematologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update_hematologia.setText("Modificar");

        btn_delete_hematologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete_hematologia.setText("Eliminar");

        btn_cancel_hematologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel_hematologia.setText("Cancelar");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_hematologia_code, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txt_hematologia_name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txt_hematologia_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancel_hematologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete_hematologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update_hematologia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_register_hematologia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 95, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register_hematologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_hematologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete_hematologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel_hematologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_hematologia_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_hematologia_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_hematologia_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 320));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Buscar:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        jPanel4.add(txt_search_hematologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        hematologias_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        jScrollPane4.setViewportView(hematologias_table);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 910, 80));

        jTabbedPane1.addTab("Hematologia", jPanel4);

        jPanel5.setBackground(new java.awt.Color(107, 210, 214));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liquidos Corporales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("Los exámenes de líquidos corporales son análisis de laboratorio que se realizan en muestras de fluidos corporales, como orina, líquido\ncefalorraquídeo, líquido sinovial (que se encuentra en las articulaciones), líquido pleural (que rodea los pulmones), líquido peritoneal\n(que se encuentra en la cavidad abdominal) y líquido amniótico (que rodea al feto durante el embarazo). Estos exámenes pueden\nayudar a diagnosticar y monitorear una variedad de condiciones médicas, como infecciones, inflamación, cáncer, trastornos\nmetabólicos y enfermedades autoinmunitarias. Los resultados de los exámenes de líquidos corporales pueden proporcionar \ninformación importante sobre la salud del cuerpo y pueden ayudar a los médicos a tomar decisiones informadas sobre el tratamiento.");
        jScrollPane5.setViewportView(jTextArea3);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Código:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Nombre:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Precio:");

        txt_liquido_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_liquido_nameActionPerformed(evt);
            }
        });

        btn_register_liquido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register_liquido.setText("Registrar");

        btn_update_liquido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update_liquido.setText("Modificar");

        btn_delete_liquido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete_liquido.setText("Eliminar");

        btn_cancel_liquido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel_liquido.setText("Cancelar");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_liquido_code, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_liquido_name, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_liquido_price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_cancel_liquido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete_liquido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel_liquido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txt_liquido_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_liquido_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_liquido_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 320));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Buscar:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        jPanel5.add(txt_search_liquidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        liquidos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        jScrollPane6.setViewportView(liquidos_table);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 910, 80));

        jTabbedPane1.addTab("Liquidos Corporales", jPanel5);

        jPanel6.setBackground(new java.awt.Color(107, 210, 214));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Molecular", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("Los exámenes moleculares en el laboratorio implican el análisis de material genético, como el ADN y el ARN, para detectar mutaciones, \nanomalías y enfermedades genéticas. Estos exámenes pueden incluir técnicas como la PCR (Reacción en Cadena de la Polimerasa), \nsecuenciación genética, análisis de microarrays y pruebas de hibridación de ácidos nucleicos (NAT). Los exámenes moleculares pueden\nutilizarse para diagnosticar enfermedades genéticas,  identificar mutaciones en tumores cancerosos, monitorear la eficacia del tratamiento\ny predecir la probabilidad de desarrollar ciertas enfermedades. Los resultados de estos exámenes son muy precisos y pueden proporcionar\ninformación valiosa para la toma de decisiones médicas y el diseño de tratamientos personalizados.");
        jScrollPane7.setViewportView(jTextArea4);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Código:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nombre:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Precio:");

        txt_molecular_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_molecular_nameActionPerformed(evt);
            }
        });

        btn_register_molecular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register_molecular.setText("Registrar");

        btn_update_molecular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update_molecular.setText("Modificar");

        btn_delete_molecular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete_molecular.setText("Eliminar");

        btn_cancel_molecular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel_molecular.setText("Cancelar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_molecular_code, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txt_molecular_name, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txt_molecular_price, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_cancel_molecular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete_molecular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update_molecular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_register_molecular, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register_molecular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_molecular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete_molecular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel_molecular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(txt_molecular_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_molecular_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_molecular_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 320));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Buscar:");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        jPanel6.add(txt_search_moleculares, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        moleculares_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        jScrollPane10.setViewportView(moleculares_table);

        jPanel6.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 910, 80));

        jTabbedPane1.addTab("Molecular", jPanel6);

        jPanel7.setBackground(new java.awt.Color(107, 210, 214));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Microbiologia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("Los exámenes de microbiología de laboratorio son pruebas realizadas en muestras biológicas, como sangre, orina o\ntejidos, para identificar y diagnosticar enfermedades causadas por microorganismos como bacterias, virus, hongos y \nparásitos. Estos exámenes pueden incluir cultivos microbiológicos, pruebas de sensibilidad a los antibióticos, pruebas\nde susceptibilidad a los antifúngicos y pruebas serológicas para detectar anticuerpos contra patógenos específicos.\nLa interpretación precisa de los resultados de estos exámenes puede ayudar a los médicos a prescribir el tratamiento\nadecuado y a prevenir la propagación de enfermedades infecciosas.");
        jScrollPane8.setViewportView(jTextArea5);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Código:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nombre:");

        txt_microbiologia_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_microbiologia_nameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Precio:");

        btn_register_microbiologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register_microbiologia.setText("Registrar");

        btn_update_microbiologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update_microbiologia.setText("Modificar");

        btn_delete_microbiologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete_microbiologia.setText("Eliminar");

        btn_cancel_microbiologia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel_microbiologia.setText("Cancelar");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txt_microbiologia_code, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(txt_microbiologia_name, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel19)
                        .addGap(26, 26, 26)
                        .addComponent(txt_microbiologia_price, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register_microbiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_cancel_microbiologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete_microbiologia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update_microbiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(btn_register_microbiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_microbiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete_microbiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel_microbiologia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_microbiologia_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txt_microbiologia_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txt_microbiologia_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 320));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Buscar:");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        jPanel7.add(txt_search_microbiologias, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        microbiologias_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        jScrollPane11.setViewportView(microbiologias_table);

        jPanel7.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 910, 80));

        jTabbedPane1.addTab("Microbiologia", jPanel7);

        jPanel8.setBackground(new java.awt.Color(107, 210, 214));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Genetica", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Código:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Nombre:");

        txt_genetica_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_genetica_nameActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Precio:");

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("Los exámenes de genética de laboratorio son pruebas realizadas en muestras biológicas, como sangre, saliva o tejidos,\npara evaluar la información genética de un individuo y detectar posibles mutaciones o variaciones genéticas que puedan estar relacionadas\ncon enfermedades hereditarias o trastornos genéticos. Estos exámenes pueden incluir pruebas de diagnóstico genético para identificar\nenfermedades genéticas específicas, análisis de polimorfismos de nucleótido simple (SNP) para evaluar el riesgo de enfermedades\npoligénicas, pruebas de portador para determinar si una persona es portadora de una mutación genética, y pruebas de paternidad para\nestablecer relaciones familiares. La interpretación de los resultados de estos exámenes requiere conocimientos especializados y puede ser\ncompleja. \nLos resultados pueden proporcionar información importante para la toma de decisiones médicas y para la planificación\nfamiliar.");
        jScrollPane9.setViewportView(jTextArea6);

        btn_register_genetica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register_genetica.setText("Registrar");
        btn_register_genetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register_geneticaActionPerformed(evt);
            }
        });

        btn_update_genetica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update_genetica.setText("Modificar");
        btn_update_genetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_geneticaActionPerformed(evt);
            }
        });

        btn_delete_genetica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete_genetica.setText("Eliminar");

        btn_cancel_genetica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel_genetica.setText("Cancelar");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txt_genetica_code, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txt_genetica_name, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel22)
                        .addGap(26, 26, 26)
                        .addComponent(txt_genetica_price, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register_genetica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_cancel_genetica, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(btn_delete_genetica, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(btn_update_genetica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register_genetica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update_genetica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete_genetica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel_genetica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txt_genetica_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txt_genetica_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txt_genetica_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel8.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 320));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Buscar:");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        jPanel8.add(txt_search_geneticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 120, -1));

        geneticas_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Precio"
            }
        ));
        jScrollPane12.setViewportView(geneticas_table);

        jPanel8.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 910, 80));

        jTabbedPane1.addTab("Genetica", jPanel8);

        jPanel9.setBackground(new java.awt.Color(107, 210, 214));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuraciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Identificación:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Nombre completo:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Nombre de usuario:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Rol:");

        cmb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Auxiliar" }));

        txt_empleado_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empleado_fullnameActionPerformed(evt);
            }
        });

        txt_empleado_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empleado_idActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel50.setText("Dirección:");

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel51.setText("Telefóno:");

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel52.setText("Correo:");

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel53.setText("Contraseña:");

        btn_register_employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register_employee.setText("Registrar");

        btn_update_employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update_employee.setText("Modificar");

        btn_delete_employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete_employee.setText("Eliminar");

        btn_cancel_employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_cancel_employee.setText("Cancelar");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(2, 2, 2)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addComponent(txt_empleado_username, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_empleado_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_empleado_id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53))))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_empleado_address, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_empleado_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_empleado_email, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_empleado_password, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancel_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_register_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txt_empleado_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50)
                    .addComponent(txt_empleado_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_register_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txt_empleado_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(txt_empleado_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txt_empleado_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(txt_empleado_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cmb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(btn_cancel_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_empleado_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 920, 270));
        jPanel9.add(txt_search_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 160, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Buscar:");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        empleados_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacíon", "Nombre", "Nombre de usuario", "Dirección", "Teléfono", "Correo", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(empleados_table);
        if (empleados_table.getColumnModel().getColumnCount() > 0) {
            empleados_table.getColumnModel().getColumn(3).setHeaderValue("Dirección");
            empleados_table.getColumnModel().getColumn(4).setHeaderValue("Teléfono");
            empleados_table.getColumnModel().getColumn(5).setHeaderValue("Correo");
            empleados_table.getColumnModel().getColumn(6).setHeaderValue("Rol");
        }

        jPanel9.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 337, 910, 130));

        jTabbedPane1.addTab("Empleados", jPanel9);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 1020, 580));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tubos.jpg"))); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hematologia_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hematologia_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hematologia_nameActionPerformed

    private void txt_liquido_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_liquido_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_liquido_nameActionPerformed

    private void txt_molecular_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_molecular_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_molecular_nameActionPerformed

    private void txt_microbiologia_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_microbiologia_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_microbiologia_nameActionPerformed

    private void txt_genetica_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_genetica_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_genetica_nameActionPerformed

    private void txt_empleado_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empleado_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empleado_fullnameActionPerformed

    private void txt_empleado_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empleado_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empleado_idActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        if(evt.getSource() == btn_logout){
            dispose();
            LoginView login = new LoginView();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_register_geneticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register_geneticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_register_geneticaActionPerformed

    private void btn_update_geneticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_geneticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_update_geneticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_cancel_employee;
    public javax.swing.JButton btn_cancel_genetica;
    public javax.swing.JButton btn_cancel_hematologia;
    public javax.swing.JButton btn_cancel_liquido;
    public javax.swing.JButton btn_cancel_microbiologia;
    public javax.swing.JButton btn_cancel_molecular;
    public javax.swing.JButton btn_cancel_quimica;
    public javax.swing.JButton btn_delete_employee;
    public javax.swing.JButton btn_delete_genetica;
    public javax.swing.JButton btn_delete_hematologia;
    public javax.swing.JButton btn_delete_liquido;
    public javax.swing.JButton btn_delete_microbiologia;
    public javax.swing.JButton btn_delete_molecular;
    public javax.swing.JButton btn_delete_quimica;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_photo;
    public javax.swing.JButton btn_register_employee;
    public javax.swing.JButton btn_register_genetica;
    public javax.swing.JButton btn_register_hematologia;
    public javax.swing.JButton btn_register_liquido;
    public javax.swing.JButton btn_register_microbiologia;
    public javax.swing.JButton btn_register_molecular;
    public javax.swing.JButton btn_register_quimica;
    public javax.swing.JButton btn_update_employee;
    public javax.swing.JButton btn_update_genetica;
    public javax.swing.JButton btn_update_hematologia;
    public javax.swing.JButton btn_update_liquido;
    public javax.swing.JButton btn_update_microbiologia;
    public javax.swing.JButton btn_update_molecular;
    public javax.swing.JButton btn_update_quimica;
    public javax.swing.JComboBox<String> cmb_rol;
    public javax.swing.JTable empleados_table;
    public javax.swing.JTable geneticas_table;
    public javax.swing.JTable hematologias_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelCotizaciones;
    public javax.swing.JLabel jLabelEmpleados;
    public javax.swing.JLabel jLabelGenetica;
    public javax.swing.JLabel jLabelHematologia;
    public javax.swing.JLabel jLabelLiquidosCorporales;
    public javax.swing.JLabel jLabelMicrobiologia;
    public javax.swing.JLabel jLabelMolecular;
    public javax.swing.JLabel jLabelQuimica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JPanel jPanelCotizaciones;
    public javax.swing.JPanel jPanelGeneticas;
    public javax.swing.JPanel jPanelHematologia;
    public javax.swing.JPanel jPanelLiquidosCorporales;
    public javax.swing.JPanel jPanelMicrobiologia;
    public javax.swing.JPanel jPanelMolecular;
    public javax.swing.JPanel jPanelQuimica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    public javax.swing.JTable liquidos_table;
    public javax.swing.JTable microbiologias_table;
    public javax.swing.JTable moleculares_table;
    public javax.swing.JTable quimicas_table;
    public javax.swing.JTextField txt_empleado_address;
    public javax.swing.JTextField txt_empleado_email;
    public javax.swing.JTextField txt_empleado_fullname;
    public javax.swing.JTextField txt_empleado_id;
    public javax.swing.JPasswordField txt_empleado_password;
    public javax.swing.JTextField txt_empleado_telephone;
    public javax.swing.JTextField txt_empleado_username;
    public javax.swing.JTextField txt_genetica_code;
    public javax.swing.JTextField txt_genetica_name;
    public javax.swing.JTextField txt_genetica_price;
    public javax.swing.JTextField txt_hematologia_code;
    public javax.swing.JTextField txt_hematologia_name;
    public javax.swing.JTextField txt_hematologia_price;
    public javax.swing.JTextField txt_liquido_code;
    public javax.swing.JTextField txt_liquido_name;
    public javax.swing.JTextField txt_liquido_price;
    public javax.swing.JTextField txt_microbiologia_code;
    public javax.swing.JTextField txt_microbiologia_name;
    public javax.swing.JTextField txt_microbiologia_price;
    public javax.swing.JTextField txt_molecular_code;
    public javax.swing.JTextField txt_molecular_name;
    public javax.swing.JTextField txt_molecular_price;
    public javax.swing.JTextField txt_quimica_code;
    public javax.swing.JTextField txt_quimica_name;
    public javax.swing.JTextField txt_quimica_price;
    public javax.swing.JTextField txt_search_empleado;
    public javax.swing.JTextField txt_search_geneticas;
    public javax.swing.JTextField txt_search_hematologia;
    public javax.swing.JTextField txt_search_liquidos;
    public javax.swing.JTextField txt_search_microbiologias;
    public javax.swing.JTextField txt_search_moleculares;
    public javax.swing.JTextField txt_search_quimica;
    // End of variables declaration//GEN-END:variables
}
